### ISSUE TITLE
Found this resource, perhaps it may help to mod the BIOS?

### ISSUE THREAD

**Issue by muhchaudhary** [bomdurup/x1c7_2020_hacintosh#4]
>Just an FYI, you can partially bypass bootguard and enable a custom BIOS on these machines now using a >Lenovo backdoor. Not sure if that gets us any closer, but if you have the hardware feel free to play around >- this should let you unlock the whitelist (you'll have to write the patch yourself, this just stops boot guard from locking up when you flash an unsigned BIOS).

>sed 's/\x4C\x4E\x56\x42\x42\x53\x45\x43\xFB\xFF/\x4C\x4E\x56\x42\x42\x53\x45\x43\xFF\xFF/g' input.rom > output.rom

>Not tested on C7, but tested on C6 and several other Skylake machines - T480, T470.

credit goes to: https://github.com/n4ru

**Comment by oceanzhang860411** [comment]
After bios mod, still stucks at [EB|#LOG:EXITBS:START]
[https://sm.ms/image/EqFCfcwrMkG1os3](https://sm.ms/image/EqFCfcwrMkG1os3)
[https://sm.ms/image/Bq8YeEdc36WopMm](https://sm.ms/image/Bq8YeEdc36WopMm)
p.s. I have a Thinkpad L13 with i5 10210u

**Comment by muhchaudhary** [comment]
Try again using open core  0.6.7. Someone with your exact laptop has got it working

**Comment by bomdurup** [comment]
too late to reply but this issue was resolved since opencore 0.6.7 as @muhchaudhary mentioned
