### ISSUE TITLE
Is CFG Lock really the issue here?

### ISSUE THREAD

**Issue by hagenest** [bomdurup/x1c7_2020_hacintosh#6]
Hey there. :)
I'm having the exact same problem with my Thinkpad L13, which also has a comet lake CPU. 
I'm wondering how are you so convinced that cfg lock is the issue? In theory `applexcpmcfglock` should work regardless of hardware, as I have been told by two devs.
- https://github.com/acidanthera/bugtracker/issues/1397
- https://github.com/acoutts/x1c7-hackintosh/issues/1#issuecomment-752804279 

It seems like the problem lies somewhere else.

**Comment by hagenest** [comment]
I got it to work thanks to the help of a kind stranger who pointed me to a chinese repo: [Repo](https://github.com/hagenest/thinkpad-l13-yoga-hackintosh/issues/2)

**Comment by bomdurup** [comment]
too late to reply, mate. Now I know this issue was solved since opencore 0.6.7

https://github.com/acidanthera/bugtracker/issues/1486#issuecomment-781062621
